export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGESTER_SUCCESS = 'REGESTER_SUCCESS';
export const REGESTER_FAIL = 'REGESTER_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCSESS = 'LOGIN_SUCSESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_FAIL = 'UPDATE_FAIL';
export const USERS_LOADED = 'USERS_LOADED';
export const ADD_QUESTION_FAIL = 'ADD_QUESTION_FAIL';
export const LOAD_QUESTIONS_FAIL = 'LOAD_QUESTIONS_FAIL';

export const DELETE_QUESTION_FAIL = 'DELETE_QUESTION_FAIL';
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const UPDATE_QUESTION_FAIL = 'UPDATE_QUESTION_FAIL';

export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';

export const UPDATE_QUESTION = 'UPDATE_CONTACT';

export const ADD_STUDENT = 'ADD_STUDENT';
export const UPDATE_UPDATE = 'UPDATE_UPDATE';
